(function(){
"use strict";
if(window.__gbGlossaryInitialized)return;window.__gbGlossaryInitialized=true;
var D={rootSelectors:["article","main[data-pagefind-body]"],proseSelectors:["p","div.reveal","[data-glossary-zone='prose']"],hydrationForbiddenSelectors:["a","abbr",".gterm","code","pre","kbd","samp","nav","figure","figcaption","caption","table","thead","tbody","tfoot","tr","th","td",".article-header",".author-card",".series-nav",".article-toc",".summary-card",".note-box",".context-bridge",".ancient-epigraph",".reading-list-section",".fact-card",".quick-fact",".key-point",".fn-marker",".tooltip",".btip",".gtip",".quiz-wrapper",".gbs2-timeline",".gbs2-next","[data-glossary-skip]","[hidden]","[data-pagefind-meta]","[data-pagefind-ignore]","h1","h2","h3","h4","h5","h6","script","style"],placementForbiddenSelectors:["nav","figure","figcaption","caption","table","thead","tbody","tfoot","tr","th","td",".article-header",".author-card",".series-nav",".article-toc",".summary-card",".note-box",".context-bridge",".ancient-epigraph",".reading-list-section",".fact-card",".quick-fact",".key-point",".fn-marker",".tooltip",".btip",".quiz-wrapper",".gbs2-timeline",".gbs2-next","[data-glossary-skip]","[hidden]","[data-pagefind-meta]","[data-pagefind-ignore]","h1","h2","h3","h4","h5","h6"],cadence:{minWordGap:1200,minBlockGap:20,maxPerArticle:3}},R=window.__gbGlossaryRuntime=window.__gbGlossaryRuntime||{},root=document.querySelector("article,main[data-pagefind-body]");
window.SiteUtils=window.SiteUtils||{};window.SiteUtils.hydrateGlossaryTerms=hydrateGlossaryTerms;
if(root)load().then(function(s){if(s){manualClean(root,s);auto(root,s);manual(root,s);tips(root)}}).catch(function(){});
document.addEventListener("gb:quiz-rendered",function(e){hydrateGlossaryTerms(e&&e.detail&&e.detail.root||document)});
function hydrateGlossaryTerms(e){e=e&&e.querySelectorAll?e:document;if(e.closest&&e.closest(".summary-card"))return Promise.resolve();return load().then(function(s){if(!s)return;manualClean(e,s);auto(e,s);manual(e,s);tips(e)})}
function norm(v){return String(v||"").toLowerCase().replace(/ё/g,"е").replace(/[‐‑‒–—−]/g,"-").replace(/\s+/g," ").trim()}
function num(v){v=Number(v);return Number.isFinite(v)?v:null}
function meta(d,k){var e=d&&d[k]||{},n=e.definition&&typeof e.definition==="object"?e.definition:{};return{category:e.category||n.category||"",categorySlug:e.categorySlug||e.category_slug||n.categorySlug||n.category_slug||"",autoHydrate:e.autoHydrate!==false&&n.autoHydrate!==false,minWordGap:num(e.minWordGap)??num(n.minWordGap),minBlockGap:num(e.minBlockGap)??num(n.minBlockGap),maxPerArticle:num(e.maxPerArticle)??num(n.maxPerArticle)}}
function load(){if(R.dict&&R.policy&&R.aliasToCanonical&&R.regex)return Promise.resolve(R);if(R.promise)return R.promise;R.promise=Promise.all([fetch("/data/glossary.json").then(function(r){return r.ok?r.json():null}),fetch("/data/glossary-policy.json").then(function(r){return r.ok?r.json():null}).catch(function(){return null})]).then(function(x){if(!x[0]||typeof x[0]!=="object")return null;var c=compile(x[0]);R.dict=x[0];R.policy=policy(x[1]);R.aliasToCanonical=c.auto;R.aliasAll=c.all;R.regex=c.regex;return R}).catch(function(){return null});return R.promise}
function policy(o){o=o&&typeof o==="object"?o:{};var old=Array.isArray(o.forbiddenSelectors)?o.forbiddenSelectors:null,c=o.cadence||{};return{rootSelectors:Array.isArray(o.rootSelectors)?o.rootSelectors:D.rootSelectors,proseSelectors:Array.isArray(o.proseSelectors)?o.proseSelectors:D.proseSelectors,hydrationForbiddenSelectors:Array.isArray(o.hydrationForbiddenSelectors)?o.hydrationForbiddenSelectors:old||D.hydrationForbiddenSelectors,placementForbiddenSelectors:Array.isArray(o.placementForbiddenSelectors)?o.placementForbiddenSelectors:D.placementForbiddenSelectors,cadence:{minWordGap:num(c.minWordGap)??D.cadence.minWordGap,minBlockGap:num(c.minBlockGap)??D.cadence.minBlockGap,maxPerArticle:num(c.maxPerArticle)??D.cadence.maxPerArticle}}}
function compile(d){var a={},all={},list=[];Object.keys(d).forEach(function(k){var e=d[k]||{},n=e.definition&&typeof e.definition==="object"?e.definition:{},xs=Array.isArray(e.aliases)?e.aliases.slice():Array.isArray(n.aliases)?n.aliases.slice():[];if(xs.indexOf(k)<0)xs.unshift(k);var m=meta(d,k);xs.forEach(function(x){var z=norm(x);if(!z)return;if(!all[z])all[z]=k;if(m.autoHydrate&&!a[z]){a[z]=k;if(list.indexOf(x)<0)list.push(x)}})});list.sort(function(x,y){return y.length-x.length});var src=list.map(esc).join("|"),re=null;if(src)try{re=new RegExp("(^|[^\\p{L}\\p{N}_])("+src+")(?=$|[^\\p{L}\\p{N}_])","giu")}catch(_){try{re=new RegExp("(^|[^а-яёА-ЯЁa-zA-Z0-9_])("+src+")(?=$|[^а-яёА-ЯЁa-zA-Z0-9_])","gi")}catch(_){}}return{auto:a,all:all,regex:re}}
function esc(v){return String(v).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function closest(n,ss){var e=n&&n.nodeType===Node.ELEMENT_NODE?n:n&&n.parentElement;if(!e)return true;return ss.some(function(s){try{return!!e.closest(s)}catch(_){return false}})}
function forbidden(n,p,type){return closest(n,p[type])}
function blocks(scope,p){var q=p.proseSelectors.join(","),xs=Array.from(scope.querySelectorAll(q)).filter(function(e){return!forbidden(e,p,"hydrationForbiddenSelectors")});return xs.filter(function(e){return!xs.some(function(o){return o!==e&&e.contains(o)})})}
function manualClean(scope,s){Array.from(scope.querySelectorAll(".gterm")).forEach(function(t){if(!forbidden(t.parentElement,s.policy,"placementForbiddenSelectors"))return;var c=t.cloneNode(true);c.querySelectorAll(".gtip").forEach(function(x){x.remove()});t.replaceWith(document.createTextNode(c.textContent||""))})}
function auto(scope,s){if(!s.regex)return;var seen={},words=0;blocks(scope,s.policy).forEach(function(b,bi){var start=words,text=b.textContent||"";words+=count(text);var w=document.createTreeWalker(b,NodeFilter.SHOW_TEXT,{acceptNode:function(e){if(e.parentElement&&e.parentElement.closest(".summary-card"))return NodeFilter.FILTER_REJECT;if(!e.nodeValue||!e.nodeValue.trim())return NodeFilter.FILTER_REJECT;return forbidden(e,s.policy,"hydrationForbiddenSelectors")?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}}),nodes=[];while(w.nextNode())nodes.push(w.currentNode);var before=0;nodes.forEach(function(n){var t=n.nodeValue,re=s.regex,last=0,changed=false,m,f=document.createDocumentFragment();re.lastIndex=0;while((m=re.exec(t))){var pre=m[1]||"",vis=m[2]||"",k=s.aliasToCanonical[norm(vis)];if(!k)continue;var at=m.index+pre.length,pos=start+before+count(t.slice(0,at));if(!allow(k,bi,pos,seen,s))continue;f.appendChild(document.createTextNode(t.slice(last,at)));f.appendChild(term(vis,k,s.dict));last=at+vis.length;changed=true;record(k,bi,pos,seen)}if(changed){f.appendChild(document.createTextNode(t.slice(last)));n.replaceWith(f)}before+=count(t)})})}
function allow(k,b,w,seen,s){var old=seen[k],m=meta(s.dict,k),c=s.policy.cadence,max=m.maxPerArticle??c.maxPerArticle,bgap=m.minBlockGap??c.minBlockGap,wgap=m.minWordGap??c.minWordGap;if(!old)return max>0;if(old.count>=max)return false;return b-old.blockIndex>=bgap&&w-old.wordPosition>=wgap}
function record(k,b,w,s){var o=s[k];s[k]={count:o?o.count+1:1,blockIndex:b,wordPosition:w}}
function count(v){var m=String(v||"").match(/[\p{L}\p{N}]+/gu);return m?m.length:0}
function term(v,k,d){var t=document.createElement("abbr");t.className="gterm";t.dataset.term=k;t.tabIndex=0;t.setAttribute("role","button");t.setAttribute("data-term-title",title(k));category(t,k,d);t.appendChild(document.createTextNode(v));t.appendChild(tip(d,k));return t}
function manual(scope,s){Array.from(scope.querySelectorAll(".gterm")).forEach(function(t){if(forbidden(t.parentElement,s.policy,"placementForbiddenSelectors"))return;var raw=t.getAttribute("data-term")||t.getAttribute("data-term-title")||first(t),k=s.aliasAll[norm(raw)]||s.aliasToCanonical[norm(raw)];if(!k)return;t.dataset.term=k;t.setAttribute("data-term-title",title(k));t.setAttribute("role","button");if(!t.hasAttribute("tabindex"))t.tabIndex=0;category(t,k,s.dict);var x=t.querySelector(".gtip");if(!x)t.appendChild(tip(s.dict,k));else upgrade(t,x,k,s.dict)})}
function first(e){var n=Array.from(e.childNodes).find(function(x){return x.nodeType===Node.TEXT_NODE&&String(x.textContent||"").trim()});return n?n.textContent:e.textContent}
function title(v){return String(v||"").replace(/^[а-яёa-z]/u,function(c){return c.toUpperCase()})}
function category(t,k,d){var m=meta(d,k);if(m.category)t.dataset.category=m.category;if(m.categorySlug)t.dataset.categorySlug=m.categorySlug}
function def(d,k){var e=d&&d[k];if(!e)return{brief:k,detail:""};var b=k;if(typeof e==="string")b=e;else if(typeof e.definition==="string")b=e.definition;else if(e.definition&&typeof e.definition.definition==="string")b=e.definition.definition;return{brief:b,detail:e&&typeof e.detail==="string"?e.detail:""}}
function tip(d,k){var m=meta(d,k),x=def(d,k),t=document.createElement("span");t.className="gtip";if(m.category)t.dataset.category=m.category;if(m.categorySlug)t.dataset.categorySlug=m.categorySlug;t.innerHTML=html(x.brief,x.detail);return t}
function html(b,d){if(!d)return safe(b);return'<span class="gtip-brief">'+safe(b)+'</span><button type="button" class="gtip-expand-btn" aria-label="Подробнее" aria-expanded="false" data-gtip-expand><span class="gtip-expand-txt">Подробнее</span><svg class="gtip-expand-ico" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true"><path d="M2 3.5 5 6.5 8 3.5" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></button><span class="gtip-detail-wrap" aria-hidden="true"><span class="gtip-detail"><span class="gtip-papyrus">'+d+'</span></span></span>'}
function safe(v){var e=document.createElement("div");e.textContent=String(v||"");return e.innerHTML}
function upgrade(t,x,k,d){if(t.dataset.gtipUpgraded==="1")return;var h=x.querySelector(".gtip-luxury__definition")||x;if(h.querySelector(".gtip-brief")){t.dataset.gtipUpgraded="1";return}var z=def(d,k),b=String(h.textContent||"").trim()||z.brief;h.innerHTML=html(b,z.detail);t.dataset.gtipUpgraded="1"}
function tips(e){if(window.SiteUtils&&typeof window.SiteUtils.initGlossaryTooltips==="function")window.SiteUtils.initGlossaryTooltips(e)}
})();
