export const LOT_TOC = [
  { id: 'sec-who-is-lot', label: 'Кто такой Лот' },
  { id: 'sec-canonical-verdict', label: 'Вердикт 2 Петра' },
  { id: 'sec-choice', label: 'Выбор равнины' },
  { id: 'sec-war', label: 'Первое избавление' },
  { id: 'sec-abraham-lot', label: 'Авраам и Лот' },
  { id: 'sec-sodom-night', label: 'Ночь в Содоме' },
  { id: 'sec-why-sodom', label: 'Грех Содома' },
  { id: 'sec-hesitation', label: 'Промедление и милость' },
  { id: 'sec-lots-wife', label: 'Жена Лота' },
  { id: 'sec-zoar', label: 'Сигор' },
  { id: 'sec-cave', label: 'Пещера' },
  { id: 'sec-moab-ammon', label: 'Моав и Аммон' },
  { id: 'sec-ruth', label: 'Руфь' },
  { id: 'sec-lot-legacy', label: 'Наследие Лота' },
  { id: 'sec-archaeology', label: 'Археология' },
  { id: 'sec-tall-el-hammam', label: 'Tall el-Hammam' },
  { id: 'sec-zoar-tradition', label: 'Цоар и традиция' },
  { id: 'sec-how-to-read', label: 'Как читать историю' },
  { id: 'sec-main-theology', label: 'Что здесь главное' },
  { id: 'sec-conclusion', label: 'Итог' },
  { id: 'sec-quiz', label: 'Проверь себя' },
  { id: 'lot-sources-title', label: 'Источники' },
] as const;
