import type { GillSeriesPageId } from './gillSeriesData';

/**
 * Gill mobile Learning sheet — «Тест» tab data contract.
 *
 * This is deliberately a flat, infinite-shuffle practice pool (Fisher–Yates
 * over the full set, no repeat of the previous cycle's last question first),
 * NOT a spaced-repetition system. A separate SYSTEM-lane wave
 * (`feat/system-learning-review-v1`, see project docs) will later layer a
 * proper SM-2 scheduler on top of stable `learningTargetId`s — this pool's
 * `id`/`category`/`sourceHref` fields are kept stable and structurally
 * clean specifically so that wave can hook in without reshaping this data.
 * Do not add scheduling/storage logic here.
 */

export type GillLearningQuizCategory =
  | 'people'
  | 'dates'
  | 'places'
  | 'works'
  | 'theology'
  | 'method'
  | 'sources';

export type GillLearningQuizItem = {
  id: string;
  category: GillLearningQuizCategory;
  question: string;
  answers: [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
  explanation: string;
  sourceHref: string;
  sourceLabel: string;
  relatedPageId?: GillSeriesPageId;
};

export const GILL_LEARNING_QUIZ: GillLearningQuizItem[] = [
  {
    id: 'gill.context.great-ejection.year',
    category: 'dates',
    question: 'В каком году произошло Великое изгнание нонконформистского духовенства?',
    answers: ['1662', '1688', '1719', '1697'],
    correctIndex: 0,
    explanation: 'В 1662 году Акт о единообразии вынудил уйти сотни нонконформистских священников — тень этого события легла на весь мир диссентеров, в котором позже служил Гилл.',
    sourceHref: '../../articles/dzhon-gill-istoricheskiy-kontekst/#sec-great-ejection',
    sourceLabel: 'Исторический контекст · Тень 1662 года',
    relatedPageId: 'context',
  },
  {
    id: 'gill.context.salters-hall.year',
    category: 'dates',
    question: 'В каком году произошёл доктринальный раскол на Солтерс-Холл?',
    answers: ['1719', '1662', '1729', '1697'],
    correctIndex: 0,
    explanation: 'Спор 1719 года о подписании тринитарных формул расколол английских диссентеров незадолго до начала служения Гилла.',
    sourceHref: '../../articles/dzhon-gill-istoricheskiy-kontekst/#sec-salters-hall',
    sourceLabel: 'Исторический контекст · Солтерс-Холл (1719)',
    relatedPageId: 'context',
  },
  {
    id: 'gill.context.particular-vs-general',
    category: 'theology',
    question: 'Что отличает партикулярных баптистов от генеральных?',
    answers: [
      'Позиция по объёму искупления Христа',
      'Отношение к крещению младенцев',
      'Организационная структура церкви',
      'Использование латинского языка в богослужении',
    ],
    correctIndex: 0,
    explanation: 'Партикулярные баптисты, к которым принадлежал Гилл, придерживались учения об ограниченном (частном) искуплении — в отличие от генеральных баптистов.',
    sourceHref: '../../articles/dzhon-gill-istoricheskiy-kontekst/#sec-particular-vs-general',
    sourceLabel: 'Исторический контекст · Партикулярные и генеральные баптисты',
    relatedPageId: 'context',
  },
  {
    id: 'gill.context.academies',
    category: 'places',
    question: 'Чем для нонконформистов были диссентерские академии?',
    answers: [
      'Альтернативой закрытым для них Оксфорду и Кембриджу',
      'Тайными типографиями',
      'Судебными органами общин',
      'Загородными резиденциями пасторов',
    ],
    correctIndex: 0,
    explanation: 'Поскольку Оксфорд и Кембридж были закрыты для нонконформистов религиозными тестами, диссентерские академии стали их основным путём к образованию.',
    sourceHref: '../../articles/dzhon-gill-istoricheskiy-kontekst/#sec-academies',
    sourceLabel: 'Исторический контекст · Диссентерские академии',
    relatedPageId: 'context',
  },
  {
    id: 'gill.man.horsleydown.years',
    category: 'dates',
    question: 'Сколько лет Гилл прослужил пастором в Хорслидауне?',
    answers: ['51 год', '32 года', '16 лет', '71 год'],
    correctIndex: 0,
    explanation: 'Гилл возглавлял общину в Хорслидауне (Саутварк) пятьдесят один год — редкий пример пожизненной оседлости для пастора его эпохи.',
    sourceHref: '../../articles/dzhon-gill-chast-1-chelovek/#part-pastor',
    sourceLabel: 'Часть I · Пасторское служение в Хорслидауне',
    relatedPageId: 'part1',
  },
  {
    id: 'gill.man.horsleydown.place',
    category: 'places',
    question: 'В каком лондонском районе Гилл возглавлял общину?',
    answers: ['Саутварк', 'Вестминстер', 'Кеттеринг', 'Гринвич'],
    correctIndex: 0,
    explanation: 'Хорслидаун находится в Саутварке — районе на южном берегу Темзы, который стал местом всего пасторского служения Гилла.',
    sourceHref: '../../articles/dzhon-gill-chast-1-chelovek/#sec-context-southwark',
    sourceLabel: 'Часть I · Исторический контекст: Саутварк',
    relatedPageId: 'part1',
  },
  {
    id: 'gill.man.ordination.year',
    category: 'dates',
    question: 'Когда состоялось рукоположение Гилла?',
    answers: ['22 марта 1720 года', '1 января 1719 года', '10 июля 1697 года', '5 мая 1729 года'],
    correctIndex: 0,
    explanation: 'Рукоположение Гилла состоялось 22 марта 1720 года — событие, подробно задокументированное в полном протоколе.',
    sourceHref: '../../articles/dzhon-gill-chast-1-chelovek/#sec-ordination-1720',
    sourceLabel: 'Часть I · Рукоположение 22 марта 1720 года',
    relatedPageId: 'part1',
  },
  {
    id: 'gill.man.education',
    category: 'people',
    question: 'Что заменило юному Гиллу формальное университетское образование?',
    answers: ['Книжная лавка', 'Диссентерская академия', 'Домашнее обучение у раввина', 'Оксфордский колледж'],
    correctIndex: 0,
    explanation: 'Не имея доступа к грамматической школе и университету, Гилл получил основы образования во многом благодаря книжной лавке в Кеттеринге.',
    sourceHref: '../../articles/dzhon-gill-chast-1-chelovek/#sec-education',
    sourceLabel: 'Часть I · Книжная лавка вместо грамматической школы',
    relatedPageId: 'part1',
  },
  {
    id: 'gill.man.goatyard-declaration.year',
    category: 'dates',
    question: 'В каком году была принята Декларация Козьего Двора?',
    answers: ['1729', '1662', '1719', '1720'],
    correctIndex: 0,
    explanation: 'Декларация Козьего Двора 1729 года зафиксировала исповедание общины Гилла — важный документ для понимания архитектуры его богословия.',
    sourceHref: '../../articles/dzhon-gill-chast-1-chelovek/#sec-goatyardDecl',
    sourceLabel: 'Часть I · Декларация Козьего Двора 1729 года',
    relatedPageId: 'part1',
  },
  {
    id: 'gill.scholar.mishnah',
    category: 'works',
    question: 'С каким источником прежде всего ассоциируется научная работа Гилла-раввиниста?',
    answers: ['Мишна', 'Талмуд Вавилонский целиком', 'Кумранские рукописи', 'Септуагинта'],
    correctIndex: 0,
    explanation: 'Гилл был известен глубокой работой с раввинистическими источниками, прежде всего с Мишной, что было редкостью среди христианских богословов его времени.',
    sourceHref: '../../articles/dzhon-gill-chast-2-uchenyi/#sec-hebrew',
    sourceLabel: 'Часть II · Раввинист — христианин с Мишной в руках',
    relatedPageId: 'part2',
  },
  {
    id: 'gill.scholar.canticles',
    category: 'works',
    question: 'Какой труд Гилла считается его самым личным сочинением?',
    answers: ['Комментарий на Песнь Песней', '«Свод богословия»', 'Комментарий на Апокалипсис', 'Трактат о крещении'],
    correctIndex: 0,
    explanation: 'Комментарий на Песнь Песней выделяется среди трудов Гилла особой личной, созерцательной интонацией.',
    sourceHref: '../../articles/dzhon-gill-chast-2-uchenyi/#sec-canticles',
    sourceLabel: 'Часть II · Песнь Песней: самый личный труд Гилла',
    relatedPageId: 'part2',
  },
  {
    id: 'gill.scholar.systematics',
    category: 'works',
    question: 'Чем примечателен «Полный свод богословия» Гилла?',
    answers: [
      'Это первая систематическая сумма богословия, написанная баптистом',
      'Это первый английский перевод Мишны',
      'Это единственный труд Гилла на латыни',
      'Это сборник проповедей его учеников',
    ],
    correctIndex: 0,
    explanation: '«Полный свод богословия» стал первой полномасштабной систематической суммой, написанной автором-баптистом.',
    sourceHref: '../../articles/dzhon-gill-chast-2-uchenyi/#sec-systematics',
    sourceLabel: 'Часть II · «Полный свод богословия»',
    relatedPageId: 'part2',
  },
  {
    id: 'gill.exegete.1tim2-4',
    category: 'method',
    question: 'Как Гилл толкует «всех людей» в 1 Тимофею 2:4?',
    answers: [
      'Как людей разных сортов и состояний, а не каждого человека без исключения',
      'Как исключительно израильский народ',
      'Как только уверовавших ко времени написания послания',
      'Как всё сотворённое, включая ангелов',
    ],
    correctIndex: 0,
    explanation: 'Гилл ограничивает «всех людей» разными сословиями и типами людей, а не абсолютной количественной универсальностью — характерный ход его экзегетического метода.',
    sourceHref: '../../articles/dzhon-gill-chast-4-ekzeget/#sec-1tim-2-4',
    sourceLabel: 'Часть III · 1 Тимофею 2:4',
    relatedPageId: 'part4',
  },
  {
    id: 'gill.exegete.2pet3-9',
    category: 'method',
    question: 'Какое слово в 2 Петра 3:9 Гилл считает ключевым для толкования стиха?',
    answers: ['Местоимение «нас/вас»', 'Слово «долготерпит»', 'Слово «погибнуть»', 'Слово «покаяние»'],
    correctIndex: 0,
    explanation: 'Гилл сосредотачивается на объёме местоимения «нас/вас» — от этого, по его аргументу, зависит верное понимание всего стиха.',
    sourceHref: '../../articles/dzhon-gill-chast-4-ekzeget/#sec-2pet-3-9',
    sourceLabel: 'Часть III · 2 Петра 3:9',
    relatedPageId: 'part4',
  },
  {
    id: 'gill.exegete.world-texts',
    category: 'method',
    question: 'Какие два стиха Гилл разбирает вместе как «мир»-тексты?',
    answers: ['Иоанна 3:16 и 1 Иоанна 2:2', 'Римлянам 9:11 и Иоанна 1:29', 'Матфея 28:19 и Деяния 1:8', 'Титу 2:11 и Евреям 2:9'],
    correctIndex: 0,
    explanation: 'Иоанна 3:16 и 1 Иоанна 2:2 разбираются Гиллом вместе как лексический вопрос об объёме слова «мир».',
    sourceHref: '../../articles/dzhon-gill-chast-4-ekzeget/#sec-world-texts',
    sourceLabel: 'Часть III · Иоанна 3:16 и 1 Иоанна 2:2',
    relatedPageId: 'part4',
  },
  {
    id: 'gill.exegete.rabbi-yohanan',
    category: 'people',
    question: 'С кем ведётся спор, названный кульминацией экзегетического метода Гилла?',
    answers: ['С раввином Йохананом', 'С Кальвином', 'С Уайтфилдом', 'С Уэсли'],
    correctIndex: 0,
    explanation: 'Спор с раввином Йохананом представлен как кульминация экзегетической работы Гилла — сочетание раввинистической эрудиции и христианской апологетики.',
    sourceHref: '../../articles/dzhon-gill-chast-4-ekzeget/#sec-rabbi-yohanan',
    sourceLabel: 'Часть III · Спор с раввином Йохананом',
    relatedPageId: 'part4',
  },
  {
    id: 'gill.exegete.rejection-vs-reprobation',
    category: 'theology',
    question: 'Какой термин Гилл предпочитает термину «reprobation» (осуждение)?',
    answers: ['«Rejection» (отвержение)', '«Damnation»', '«Exclusion»', '«Condemnation»'],
    correctIndex: 0,
    explanation: 'Гилл проводит различие между «rejection» и «reprobation» — терминологическая точность, важная для его аргумента.',
    sourceHref: '../../articles/dzhon-gill-chast-4-ekzeget/#sec-rejection',
    sourceLabel: 'Часть III · Отвержение, а не reprobation',
    relatedPageId: 'part4',
  },
  {
    id: 'gill.exegete.duty-faith',
    category: 'theology',
    question: 'Против какого ярлыка направлен раздел о «долге веры»?',
    answers: ['Против ярлыка «гипер»', 'Против ярлыка «либерал»', 'Против ярлыка «арминианин»', 'Против ярлыка «социнианин»'],
    correctIndex: 0,
    explanation: 'Раздел о долге веры защищает Гилла от упрощённого ярлыка «гипер», уточняя, в чём именно состоит его позиция.',
    sourceHref: '../../articles/dzhon-gill-chast-4-ekzeget/#sec-duty-faith',
    sourceLabel: 'Часть III · Долг веры: против ярлыка «гипер»',
    relatedPageId: 'part4',
  },
  {
    id: 'gill.legacy.hypercalvinism',
    category: 'theology',
    question: 'Что называется самым спорным элементом наследия Гилла?',
    answers: ['Обвинение в гиперкальвинизме', 'Работа с Мишной', 'Комментарий на Песнь Песней', 'Служение в Хорслидауне'],
    correctIndex: 0,
    explanation: 'Гиперкальвинизм — самая обсуждаемая и спорная часть наследия Гилла, требующая аккуратного разбора, а не ярлыка.',
    sourceHref: '../../articles/dzhon-gill-chast-3-nasledie/#sec-controversy',
    sourceLabel: 'Часть IV · Гиперкальвинизм — спорное наследие',
    relatedPageId: 'part3',
  },
  {
    id: 'gill.legacy.spurgeon',
    category: 'people',
    question: 'Кто из известных проповедников XIX века одновременно и наследовал Гиллу, и критиковал его?',
    answers: ['Чарльз Сперджен', 'Джон Уэсли', 'Джонатан Эдвардс', 'Джордж Уайтфилд'],
    correctIndex: 0,
    explanation: 'Сперджен представлен как наследник Гилла, который при этом оставался независимым критиком некоторых сторон его богословия.',
    sourceHref: '../../articles/dzhon-gill-chast-3-nasledie/#sec-spurgeon-legacy',
    sourceLabel: 'Часть IV · Сперджен — наследник и независимый критик',
    relatedPageId: 'part3',
  },
  {
    id: 'gill.legacy.toplady',
    category: 'people',
    question: 'Кто оставил памятный отзыв о Гилле под образами «Чёрного Принца» и Мальборо?',
    answers: ['Огастус Топлэди', 'Джон Риппон', 'Чарльз Сперджен', 'Джонатан Эдвардс'],
    correctIndex: 0,
    explanation: 'Топлэди сравнивает Гилла с фигурами Чёрного Принца и Мальборо — образный современный отзыв о масштабе его личности.',
    sourceHref: '../../articles/dzhon-gill-chast-3-nasledie/#sec-toplady-memoir',
    sourceLabel: 'Часть IV · Топлэди о Гилле',
    relatedPageId: 'part3',
  },
  {
    id: 'gill.legacy.rippon',
    category: 'people',
    question: 'Кто сказал о смерти Гилла: «Столь великого плача в мире»?',
    answers: ['Джон Риппон', 'Огастус Топлэди', 'Чарльз Сперджен', 'Джон Уэсли'],
    correctIndex: 0,
    explanation: 'Джон Риппон, преемник Гилла на кафедре, оставил это свидетельство о масштабе скорби после его смерти.',
    sourceHref: '../../articles/dzhon-gill-chast-3-nasledie/#sec-ordination-rippon',
    sourceLabel: 'Часть IV · Риппон: «Столь великого плача в мире»',
    relatedPageId: 'part3',
  },
  {
    id: 'gill.legacy.islam',
    category: 'sources',
    question: 'Какая тема разбирается в разделе «Гилл и ислам»?',
    answers: ['Работа Гилла с текстом Корана', 'Переписка Гилла с османскими богословами', 'Путешествие Гилла на Ближний Восток', 'Перевод Корана самим Гиллом'],
    correctIndex: 0,
    explanation: 'Раздел показывает, что Гилл держал Коран на своём пасторском столе как часть научной эрудиции, необходимой для полемики и толкования.',
    sourceHref: '../../articles/dzhon-gill-chast-3-nasledie/#sec-gill-islam-detail',
    sourceLabel: 'Часть IV · Гилл и ислам',
    relatedPageId: 'part3',
  },
  {
    id: 'gill.legacy.rediscovery',
    category: 'dates',
    question: 'К какому периоду относится современная реабилитация Гилла, названная «Проектом Джона Гилла»?',
    answers: ['2023–2025', '1997–1999', '2010–2012', '1971–1973'],
    correctIndex: 0,
    explanation: '«Проект Джона Гилла» (2023–2025) обозначает недавний виток научного интереса к наследию Гилла и его переоценке.',
    sourceHref: '../../articles/dzhon-gill-chast-3-nasledie/#sec-gill-muller-rediscovery',
    sourceLabel: 'Часть IV · Современная реабилитация',
    relatedPageId: 'part3',
  },
  {
    id: 'gill.legacy.america',
    category: 'places',
    question: 'На какой фонд повлияло наследие Гилла в Америке?',
    answers: ['Фонд партикулярных баптистов', 'Фонд генеральных баптистов', 'Пуританский фонд Новой Англии', 'Методистский миссионерский фонд'],
    correctIndex: 0,
    explanation: 'Влияние Гилла прослеживается в становлении американского Фонда партикулярных баптистов.',
    sourceHref: '../../articles/dzhon-gill-chast-3-nasledie/#sec-america',
    sourceLabel: 'Часть IV · Влияние на Америку',
    relatedPageId: 'part3',
  },
  {
    id: 'gill.reference.lifespan',
    category: 'dates',
    question: 'Каковы годы жизни Джона Гилла?',
    answers: ['1697–1771', '1662–1729', '1719–1789', '1670–1740'],
    correctIndex: 0,
    explanation: 'Джон Гилл родился в 1697 году и умер в 1771 году — эти даты открывают весь Справочник по его жизни и служению.',
    sourceHref: '../../articles/dzhon-gill-spravochnik/#sec-timeline',
    sourceLabel: 'Справочник · Хронология жизни и служения',
    relatedPageId: 'spravochnik',
  },
  {
    id: 'gill.reference.body-structure',
    category: 'works',
    question: 'Какой труд Гилла описывает раздел «Структура «Свода богословия»»?',
    answers: ['«Полный свод богословия»', 'Комментарий на Песнь Песней', 'Декларацию Козьего Двора', 'Протокол рукоположения 1720 года'],
    correctIndex: 0,
    explanation: 'Раздел разбирает внутреннюю структуру главного систематического труда Гилла — «Полного свода богословия».',
    sourceHref: '../../articles/dzhon-gill-spravochnik/#sec-body-structure',
    sourceLabel: 'Справочник · Структура «Свода богословия»',
    relatedPageId: 'spravochnik',
  },
  {
    id: 'gill.reference.disputes',
    category: 'sources',
    question: 'Для чего в Справочнике выделен раздел «Спорные темы и как их читать»?',
    answers: [
      'Чтобы дать корректный подход к дискуссионным вопросам о наследии Гилла',
      'Чтобы перечислить все критические рецензии на Гилла',
      'Чтобы привести список его судебных тяжб',
      'Чтобы описать споры Гилла с издателями',
    ],
    correctIndex: 0,
    explanation: 'Раздел «Спорные темы» отделяет сам текст и позицию Гилла от современной оценки, чтобы читатель мог судить обоснованно.',
    sourceHref: '../../articles/dzhon-gill-spravochnik/#sec-disputes',
    sourceLabel: 'Справочник · Спорные темы и как их читать',
    relatedPageId: 'spravochnik',
  },
  {
    id: 'gill.reference.terms',
    category: 'theology',
    question: 'Зачем в Справочнике нужен раздел «Богословский словарь эпохи»?',
    answers: [
      'Чтобы объяснить термины, необходимые для понимания текстов Гилла',
      'Чтобы перечислить географические названия XVIII века',
      'Чтобы дать список сокращений латинских цитат',
      'Чтобы описать музыкальные термины гимнов эпохи',
    ],
    correctIndex: 0,
    explanation: 'Словарь эпохи собирает ключевые богословские понятия — необходимый инструмент для чтения самого Гилла, а не только текстов о нём.',
    sourceHref: '../../articles/dzhon-gill-spravochnik/#sec-terms',
    sourceLabel: 'Справочник · Богословский словарь эпохи',
    relatedPageId: 'spravochnik',
  },
  {
    id: 'gill.man.daughter-sermon',
    category: 'works',
    question: 'По какому поводу Гилл произнёс проповедь, разбирающую богословие скорби?',
    answers: ['На похоронах собственной дочери', 'На похоронах прихожанина-издателя', 'В день рукоположения', 'На годовщину общины'],
    correctIndex: 0,
    explanation: 'Проповедь Гилла на похоронах дочери сочетает личное горе и богословскую рефлексию о скорби.',
    sourceHref: '../../articles/dzhon-gill-chast-1-chelovek/#sec-daughter-sermon',
    sourceLabel: 'Часть I · Проповедь отца на похоронах дочери',
    relatedPageId: 'part1',
  },
  {
    id: 'gill.exegete.seven-texts',
    category: 'method',
    question: 'Сколько «универсальных» текстов Гилл разбирает подряд в своём экзегетическом методе?',
    answers: ['Семь', 'Три', 'Двенадцать', 'Пять'],
    correctIndex: 0,
    explanation: 'Раздел «Семь универсальных текстов» демонстрирует применение метода Гилла к серии спорных мест Писания со словами «все»/«мир».',
    sourceHref: '../../articles/dzhon-gill-chast-4-ekzeget/#sec-seven-texts',
    sourceLabel: 'Часть III · Семь «универсальных» текстов',
    relatedPageId: 'part4',
  },
  {
    id: 'gill.exegete.method-coordinates',
    category: 'method',
    question: 'Сколько «координат» составляют герменевтический метод Гилла по структуре статьи?',
    answers: ['Пять', 'Три', 'Семь', 'Две'],
    correctIndex: 0,
    explanation: 'Раздел «Герменевтический метод: пять координат» задаёт рамку, в которой далее разбираются конкретные спорные тексты.',
    sourceHref: '../../articles/dzhon-gill-chast-4-ekzeget/#sec-method',
    sourceLabel: 'Часть III · Герменевтический метод: пять координат',
    relatedPageId: 'part4',
  },
];
