/**
 * baptistSeriesConfig.ts — серия «Баптисты России · История ЕХБ» на общем
 * series-движке (третий инстанс: Гилл → Сердце → Баптисты).
 *
 * КАРКАС для наполнения: контент сырой, агенты будут добавлять/уточнять
 * статьи, но обвязка (рельс, аккордеон, бары, оверлеи) — единый канонный
 * движок с уникальной темой 'samizdat' (подпольная печать гонимой церкви:
 * газетная бумага, гектографные фиолетовые чернила, цензорский штамп).
 * Чтобы добавить часть — допиши элемент в BAPTIST_ITEMS и страницу в pages.
 */
import { SERIES_CONFIGS, type SeriesConfig, type SeriesItem, type SeriesPageChromeData, defineSeriesConfig } from './seriesConfig';

const BAPTIST_ITEMS: SeriesItem[] = [
  {
    id: 'noch-na-kure',
    mark: { kind: 'roman', value: 'I' },
    title: 'Часть I. Ночь на Куре',
    shortTitle: '1867 · Воронин, Кальвейт и первая община',
    href: '/baptisty-rossii/noch-na-kure/',
    readingTime: '18 мин',
  },
  {
    id: 'yuzhnaya-shtunda',
    mark: { kind: 'roman', value: 'II' },
    title: 'Часть II. Южная штунда',
    shortTitle: '1867–1870 · Рябошапка, Ратушный, первые крещения',
    href: '/baptisty-rossii/yuzhnaya-shtunda/',
    readingTime: '20 мин',
  },
  {
    id: 'dva-sezda-1884',
    mark: { kind: 'roman', value: 'III' },
    title: 'Часть III. Две развилки 1884',
    shortTitle: '1884 · Петербург и Ново-Васильевка',
    href: '/baptisty-rossii/dva-sezda-1884/',
    readingTime: '17 мин',
  },
  {
    id: 'peterburgskaya-liniya',
    mark: { kind: 'roman', value: 'IV' },
    title: 'Часть IV. Петербургская линия',
    shortTitle: '1874–1911 · Редсток, Пашков, Проханов',
    href: '/baptisty-rossii/peterburgskaya-liniya/',
    readingTime: '21 мин',
  },
  {
    id: 'goneniya-i-sovest',
    mark: { kind: 'roman', value: 'V' },
    title: 'Часть V. Свобода совести',
    shortTitle: '1919–1929 · Военный вопрос и гонения',
    href: '/baptisty-rossii/goneniya-i-sovest/',
    readingTime: '24 мин',
  },
  {
    id: 'sovetskaya-noch',
    mark: { kind: 'roman', value: 'VI' },
    title: 'Часть VI. Советская ночь',
    shortTitle: '1929–1937 · Закон 1929 и репрессии',
    href: '/baptisty-rossii/sovetskaya-noch/',
    readingTime: '28 мин',
  },
  {
    id: 'vsehib-1944',
    mark: { kind: 'roman', value: 'VII' },
    title: 'Часть VII. Один союз',
    shortTitle: '1944 · ВСЕХиБ под надзором',
    href: '/baptisty-rossii/vsehib-1944/',
    readingTime: '26 мин',
  },
  {
    id: 'iniciativnaya-gruppa',
    mark: { kind: 'roman', value: 'VIII' },
    title: 'Часть VIII. Инициативная группа',
    shortTitle: '1960–1966 · Путь к Совету Церквей',
    href: '/baptisty-rossii/iniciativnaya-gruppa/',
    readingTime: '25 мин',
  },
  {
    id: 'podpolnaya-pechat',
    mark: { kind: 'roman', value: 'IX' },
    title: 'Часть IX. Подпольная печать',
    shortTitle: '1966–1971 · Вестники, «Христианин», узники',
    href: '/baptisty-rossii/podpolnaya-pechat/',
    readingTime: '23 мин',
  },
  {
    id: 'spravochnik',
    mark: { kind: 'label', value: 'Справ.' },
    title: 'Справочник',
    shortTitle: 'Люди, даты, документы, источники',
    href: '/baptisty-rossii/spravochnik/',
    readingTime: '27 мин', ribbon: { word: 'Справочник', ornament: 'book', variant: 'reference' },
  },
];

const BAPTIST_PAGES: Record<string, SeriesPageChromeData> = {
  'noch-na-kure': {
    id: 'noch-na-kure',
    label: 'Воронин и ночь на Куре',
    title: 'Воронин и ночь на Куре',
    mobileSection: 'Молоканский поиск до баптистского имени',
    partLabel: 'Часть I · Содержание',
    readingProgressDoneMin: 0,
    readingProgressPartMin: 18,
    readingProgressTotalMin: 229,
    railNowTitle: 'Воронин и ночь на Куре',
    railCover: '../../images/baptisty-rossii/cover-01-kura.webp',
    partDialogLabel: 'Часть I · Ночь на Куре',
    partToc: [
      { href: '#molokan-search', label: 'Молоканский поиск до баптистского имени', level: 2, current: true, },
      { href: '#kalweit-deliakov', label: 'Кальвейт, Деляков и фраза о трёх народах', level: 2, },
      { href: '#kalweit-primary-1869', label: 'Что говорит первичный источник 1869 года', level: 2, },
      { href: '#first-in-what-sense', label: 'Первый — но в каком смысле?', level: 2, },
      { href: '#tiflis-to-russia', label: 'Как Тифлис стал началом всероссийской истории', level: 2, },
      { href: '#not-myth', label: 'Что здесь нельзя превращать в миф', level: 2, },
    ],
  },
  'yuzhnaya-shtunda': {
    id: 'yuzhnaya-shtunda',
    label: 'Южная штунда и первые крещения',
    title: 'Южная штунда и первые крещения',
    mobileSection: 'Штунда не как карикатура',
    partLabel: 'Часть II · Содержание',
    readingProgressDoneMin: 18,
    readingProgressPartMin: 20,
    readingProgressTotalMin: 229,
    railNowTitle: 'Южная штунда и первые крещения',
    railCover: '../../images/baptisty-rossii/cover-02-shtunda.webp',
    partDialogLabel: 'Часть II · Южная штунда',
    partToc: [
      { href: '#stunda-not-caricature', label: 'Штунда не как карикатура', level: 2, current: true, },
      { href: '#chain', label: 'Цепочка крещений', level: 2, },
      { href: '#missionary-magazine', label: 'Что показывают письма 1870 года', level: 2, },
      { href: '#official-reports', label: 'Что добавляют официальные рапорты', level: 2, },
      { href: '#why-south-matters', label: 'Почему юг важен для всей серии', level: 2, },
    ],
  },
  'dva-sezda-1884': {
    id: 'dva-sezda-1884',
    label: 'Петербург и Ново-Васильевка: две развилки 1884 года',
    title: 'Петербург и Ново-Васильевка: две развилки 1884 года',
    mobileSection: 'Петербург: широкое евангельское совещание',
    partLabel: 'Часть III · Содержание',
    readingProgressDoneMin: 38,
    readingProgressPartMin: 17,
    readingProgressTotalMin: 229,
    railNowTitle: 'Петербург и Ново-Васильевка: две развилки 1884 года',
    railCover: '../../images/baptisty-rossii/cover-03-1884.webp',
    partDialogLabel: 'Часть III · Две развилки 1884',
    partToc: [
      { href: '#petersburg', label: 'Петербург: широкое евангельское совещание', level: 2, current: true, },
      { href: '#state-response', label: 'Чем ответило государство', level: 2, },
      { href: '#novo-vasilievka', label: 'Ново-Васильевка: рождение союза', level: 2, },
      { href: '#pavlov-rozhdestvensky-1884', label: 'Что добавляет ранний пересказ Павлова', level: 2, },
      { href: '#two-congresses', label: 'Почему два съезда надо держать раздельно', level: 2, },
      { href: '#two-models', label: 'Две модели, которые останутся надолго', level: 2, },
    ],
  },
  'peterburgskaya-liniya': {
    id: 'peterburgskaya-liniya',
    label: 'Петербургское пробуждение: Редсток, Пашков и Проханов',
    title: 'Петербургское пробуждение: Редсток, Пашков и Проханов',
    mobileSection: 'Редсток: вопрос о личном спасении',
    partLabel: 'Часть IV · Содержание',
    readingProgressDoneMin: 55,
    readingProgressPartMin: 21,
    readingProgressTotalMin: 229,
    railNowTitle: 'Петербургское пробуждение: Редсток, Пашков и Проханов',
    railCover: '../../images/baptisty-rossii/cover-04-peterburg.webp',
    partDialogLabel: 'Часть IV · Петербургская линия',
    partToc: [
      { href: '#redstock', label: 'Редсток: вопрос о личном спасении', level: 2, current: true, },
      { href: '#pashkov', label: 'Пашков: салон становится кафедрой', level: 2, },
      { href: '#practice', label: 'Евангелие выходит из гостиной', level: 2, },
      { href: '#korf-liven-kargel', label: 'Корф, Ливены, Каргель и Бедекер', level: 2, },
      { href: '#pashkov-papers', label: 'Архив Пашкова: не легенда, а корпус документов', level: 2, },
      { href: '#1884-exile', label: '1884: Петербургский удар', level: 2, },
      { href: '#prokhanov', label: 'Проханов: наследник Петербурга', level: 2, },
      { href: '#congress-1911', label: 'Съезд 1911 года: у линии появляется устав', level: 2, },
      { href: '#prokhanov-man', label: 'Человек за союзом: гимнограф в изгнании', level: 2, },
      { href: '#why-it-matters', label: 'Почему это важно для всей серии', level: 2, },
    ],
  },
  'goneniya-i-sovest': {
    id: 'goneniya-i-sovest',
    label: 'Свобода совести и военный вопрос',
    title: 'Свобода совести и военный вопрос',
    mobileSection: 'Что значит «военный вопрос»',
    partLabel: 'Часть V · Содержание',
    readingProgressDoneMin: 76,
    readingProgressPartMin: 24,
    readingProgressTotalMin: 229,
    railNowTitle: 'Свобода совести и военный вопрос',
    railCover: '../../images/baptisty-rossii/cover-05-conscience.webp',
    partDialogLabel: 'Часть V · Свобода совести',
    partToc: [
      { href: '#what-is-military-question', label: 'Что значит «военный вопрос»', level: 2, current: true, },
      { href: '#decree-1919', label: '1919: окно для совести', level: 2, },
      { href: '#ogpu-1923', label: '1923: совесть становится делом ОГПУ', level: 2, },
      { href: '#savelyev', label: 'Савельев: подпись, покаяние и Соловки', level: 2, },
      { href: '#baptist-congress-1923', label: 'XXV съезд баптистов: совесть вместо приказа', level: 2, },
      { href: '#tuchkov', label: 'Тучков: расколоть и остановить рост', level: 2, },
      { href: '#moscow-response', label: 'Московская община отвечает', level: 2, },
      { href: '#return-1926', label: '1926: возвращение к формуле 1905 или капитуляция?', level: 2, },
      { href: '#after-1929', label: '1929: право совести как трудовой рычаг', level: 2, },
      { href: '#five-reactions', label: 'Пять моделей ответа на гонения', level: 2, },
      { href: '#postwar-line', label: '1945 и дальше: официальная линия меняется', level: 2, },
      { href: '#why-now', label: 'Почему это важно', level: 2, },
    ],
  },
  'sovetskaya-noch': {
    id: 'sovetskaya-noch',
    label: 'Советская ночь: закон 1929 года и репрессии',
    title: 'Советская ночь: закон 1929 года и репрессии',
    mobileSection: 'Послереволюционное окно',
    partLabel: 'Часть VI · Содержание',
    readingProgressDoneMin: 100,
    readingProgressPartMin: 28,
    readingProgressTotalMin: 229,
    railNowTitle: 'Советская ночь: закон 1929 года и репрессии',
    railCover: '../../images/baptisty-rossii/cover-06-soviet-night.webp',
    partDialogLabel: 'Часть VI · Советская ночь',
    partToc: [
      { href: '#open-window', label: 'Послереволюционное окно', level: 2, current: true, },
      { href: '#enemy-image', label: 'Перед законом пришёл образ врага', level: 2, },
      { href: '#law-1929', label: 'Закон 1929: культ вместо братства', level: 2, },
      { href: '#nkvd-instruction', label: 'Инструкция НКВД №328: машина сжатия', level: 2, },
      { href: '#press-closed', label: 'Закрытие печати и курсов', level: 2, },
      { href: '#union-destroyed', label: 'Разрушение Союза баптистов', level: 2, },
      { href: '#vsekh', label: 'Союз евангельских христиан', level: 2, },
      { href: '#prayer-houses', label: 'Молитвенные дома и подполье', level: 2, },
      { href: '#great-terror', label: 'Большой террор', level: 2, },
      { href: '#war-turn', label: 'Война как поворот', level: 2, },
      { href: '#why-1944', label: 'Почему 1944 стал возможен', level: 2, },
      { href: '#conclusion', label: 'Что осталось после ночи', level: 2, },
    ],
  },
  'vsehib-1944': {
    id: 'vsehib-1944',
    label: 'ВСЕХБ 1944: один союз под надзором',
    title: 'ВСЕХБ 1944: один союз под надзором',
    mobileSection: 'До 1944: две реки',
    partLabel: 'Часть VII · Содержание',
    readingProgressDoneMin: 128,
    readingProgressPartMin: 26,
    readingProgressTotalMin: 229,
    railNowTitle: 'ВСЕХБ 1944: один союз под надзором',
    railCover: '../../images/baptisty-rossii/cover-07-vsehib.webp',
    partDialogLabel: 'Часть VII · Один союз',
    partToc: [
      { href: '#before-1944', label: 'До 1944: две реки', level: 2, current: true, },
      { href: '#ruins', label: '1930-е: объединялись не процветающие союзы', level: 2, },
      { href: '#year-1942', label: '1942: совместная работа до совещания', level: 2, },
      { href: '#council-state', label: 'Совет по делам религиозных культов', level: 2, },
      { href: '#moscow-26', label: 'Москва, 26 октября 1944', level: 2, },
      { href: '#two-sticks', label: 'Два жезла Жидкова', level: 2, },
      { href: '#resolution', label: 'Резолюция 27 октября', level: 2, },
      { href: '#position', label: 'Положение о Союзе', level: 2, },
      { href: '#vsehib', label: 'Состав ВСЕХиБ', level: 2, },
      { href: '#journal', label: '«Братский Вестник»: один журнал для одного Союза', level: 2, },
      { href: '#unity-day', label: '1945: День единства', level: 2, },
      { href: '#pentecostals', label: '1945: ХВЕ и вопрос языков', level: 2, },
      { href: '#baltics', label: 'Прибалтика и расширение Союза', level: 2, },
      { href: '#blessing-tension', label: 'Благословение и напряжение', level: 2, },
    ],
  },
  'iniciativnaya-gruppa': {
    id: 'iniciativnaya-gruppa',
    label: 'Инициативная группа: путь к Совету Церквей',
    title: 'Инициативная группа: путь к Совету Церквей',
    mobileSection: 'От монолита к трещинам',
    partLabel: 'Часть VIII · Содержание',
    readingProgressDoneMin: 154,
    readingProgressPartMin: 25,
    readingProgressTotalMin: 229,
    railNowTitle: 'Инициативная группа: путь к Совету Церквей',
    railCover: '../../images/baptisty-rossii/cover-08-initiative.webp',
    partDialogLabel: 'Часть VIII · Инициативная группа',
    partToc: [
      { href: '#from-monolith', label: 'От монолита к трещинам', level: 2, current: true, },
      { href: '#position-1960', label: 'Положение ВСЕХБ 1960', level: 2, },
      { href: '#instruction-letter', label: 'Инструктивное письмо: остановить рост', level: 2, },
      { href: '#initiative-1961', label: '13 августа 1961: послание Президиуму ВСЕХБ', level: 2, },
      { href: '#first-letter-church', label: '23 августа 1961: первое послание к Церкви', level: 2, },
      { href: '#vsehb-answer', label: 'ВСЕХБ отвечает', level: 2, },
      { href: '#orgkomitet', label: 'От Инициативной группы к Оргкомитету', level: 2, },
      { href: '#council-1965', label: '18–19 сентября 1965: Совет Церквей', level: 2, },
      { href: '#council-members', label: 'Одиннадцать членов Совета', level: 2, },
      { href: '#may-1966', label: 'Май 1966: делегация к ЦК КПСС', level: 2, },
      { href: '#vins-khorev', label: '19 мая: Винс и Хорев', level: 2, },
      { href: '#awakening-or-split', label: 'Пробуждение или раскол?', level: 2, },
    ],
  },
  'podpolnaya-pechat': {
    id: 'podpolnaya-pechat',
    label: 'Подпольная печать: Вестники, «Христианин» и память узников',
    title: 'Подпольная печать: Вестники, «Христианин» и память узников',
    mobileSection: 'После 1966: церкви нужен голос',
    partLabel: 'Часть IX · Содержание',
    readingProgressDoneMin: 179,
    readingProgressPartMin: 23,
    readingProgressTotalMin: 229,
    railNowTitle: 'Подпольная печать: Вестники, «Христианин» и память узников',
    railCover: '../../images/baptisty-rossii/cover-09-samizdat.webp',
    partDialogLabel: 'Часть IX · Подпольная печать',
    partToc: [
      { href: '#voice-after-1966', label: 'После 1966: церкви нужен голос', level: 2, current: true, },
      { href: '#bratskiy-listok', label: 'Братский листок', level: 2, },
      { href: '#vestnik-spasenia', label: 'Вестник спасения', level: 2, },
      { href: '#vestnik-istiny', label: 'Вестник истины', level: 2, },
      { href: '#instruction-memory', label: 'Инструктивное письмо как память травмы', level: 2, },
      { href: '#relatives-council', label: 'Совет родственников узников', level: 2, },
      { href: '#lydia-vins', label: 'Лидия Винс', level: 2, },
      { href: '#legal-request-1966', label: '1966: просьба о легальной печати', level: 2, },
      { href: '#christian-publisher', label: '1971: издательство «Христианин»', level: 2, },
      { href: '#how-they-printed', label: 'Как печатали', level: 2, },
      { href: '#what-printed', label: 'Что печатали', level: 2, },
      { href: '#printing-raids', label: 'Разгромы типографий', level: 2, },
      { href: '#samizdat-ecclesiology', label: 'Почему самиздат был экклезиологией', level: 2, },
    ],
  },
  'spravochnik': {
    id: 'spravochnik',
    label: 'Справочник источников',
    title: 'Справочник источников',
    mobileSection: 'Уровни источников A/B/C/D',
    partLabel: 'Справочник · Содержание',
    readingProgressDoneMin: 202,
    readingProgressPartMin: 27,
    readingProgressTotalMin: 229,
    railNowTitle: 'Справочник источников',
    railCover: '../../images/baptisty-rossii/cover-10-reference.webp',
    partDialogLabel: 'Справочник · Справочник',
    partToc: [
      { href: '#source-levels', label: 'Уровни источников A/B/C/D', level: 2, current: true, },
      { href: '#people', label: 'Люди: кто уже введён в серию, кого держать на карте', level: 2, },
      { href: '#timeline', label: 'Даты: рабочая хронология серии', level: 2, },
      { href: '#documents', label: 'Документы: уже опираемся и ещё ищем', level: 2, },
      { href: '#disputed-facts', label: 'Спорные факты и редакционные предохранители', level: 2, },
      { href: '#map-backlog', label: 'Очередь правок 3D-карты', level: 2, },
      { href: '#transferred', label: 'Что уже перенесено в статьи', level: 2, },
      { href: '#what-to-search-next', label: 'Что копать дальше', level: 2, },
      { href: '#glossary', label: 'Глоссарий коротко', level: 2, },
    ],
  },
};

export const BAPTIST_SERIES: SeriesConfig = defineSeriesConfig({
  seriesId: 'russian-baptism',
  seriesTitle: 'Баптисты России',
  seriesTitleFull: 'Баптисты России · История ЕХБ',
  railBackHref: '../',
  theme: 'samizdat',
  quiz: [],
  breadcrumbParent: { label: 'Баптисты России', href: '../' },
  items: BAPTIST_ITEMS,
  pages: BAPTIST_PAGES,
});

// Регистрируем инстанс в общем реестре движка.
SERIES_CONFIGS[BAPTIST_SERIES.seriesId] = BAPTIST_SERIES;
