/**
 * pastorSeriesConfig.ts — серия «Тёмная сторона кафедры» на общем reader engine.
 *
 * Каноническая архитектура серии разделяет два яруса:
 *  - нумерованное богословско-пастырское ядро I–IX;
 *  - документальные досье (label), которые проверяют тезисы на реальных кейсах,
 *    но не занимают номер в богословском ядре.
 *
 * «Диотрефы нашего времени» сохраняют стабильный URL и reader chrome как
 * «Досье A». Канон I–IX зафиксирован в research/pastor-series/MASTER-PLAN.md.
 */
import { SERIES_CONFIGS, type SeriesConfig, defineSeriesConfig } from './seriesConfig';

const CORE_TOTAL_MIN = 321;

export const PASTOR_SERIES: SeriesConfig = defineSeriesConfig({
  seriesId: 'pastor-series',
  seriesTitle: 'Тёмная сторона кафедры',
  seriesTitleFull: 'Тёмная сторона кафедры',
  railBackHref: '../../pastor-series/',
  quiz: [],
  breadcrumbParent: { label: 'Тёмная сторона кафедры', href: '../../pastor-series/' },
  items: [
    {
      id: 'antisovetov',
      mark: { kind: 'roman', value: 'I' },
      title: 'Часть I. 20 антисоветов пастору',
      shortTitle: 'Диагностика · 20 антисоветов',
      href: '/articles/20-antisovetov-pastoru/',
      readingTime: '67 мин',
    },
    {
      id: 'anatomiya',
      mark: { kind: 'roman', value: 'II' },
      title: 'Часть II. Анатомия падения',
      shortTitle: 'Анатомия падения · пять стадий',
      href: '/articles/anatomiya-padeniya-pyat-stadiy/',
      readingTime: '29 мин',
    },
    {
      id: 'teksty',
      mark: { kind: 'roman', value: 'III' },
      title: 'Часть III. Тексты Писания, которыми манипулируют',
      shortTitle: 'Тексты Писания · границы применения',
      href: '/articles/teksty-pisaniya-kotorymi-manipuliruyut/',
      readingTime: '36 мин',
    },
    {
      id: 'sem-tipov',
      mark: { kind: 'roman', value: 'IV' },
      title: 'Часть IV. Семь типов учителей и лидеров',
      shortTitle: 'Семь типов · различение лидеров',
      href: '/articles/sem-tipov-razlichenie-uchiteley/',
      readingTime: '30 мин',
    },
    {
      id: 'disciplina',
      mark: { kind: 'roman', value: 'V' },
      title: 'Часть V. Церковная дисциплина: власть, границы и защита',
      shortTitle: 'Дисциплина · власть и защита',
      href: '/articles/cerkovnaya-disciplina-vlast-granicy-zashchita/',
      readingTime: '34 мин',
    },
    {
      id: 'kogda-uhodit',
      mark: { kind: 'roman', value: 'VI' },
      title: 'Часть VI. Когда говорить, молчать, уходить или оставаться',
      shortTitle: 'Когда говорить · когда уходить',
      href: '/articles/kogda-uhodit-kogda-ostavatsya/',
      readingTime: '33 мин',
    },
    {
      id: 'vernye',
      mark: { kind: 'roman', value: 'VII' },
      title: 'Часть VII. Верные и неизвестные: здоровое пастырство',
      shortTitle: 'Верные и неизвестные · здоровый пастор',
      href: '/articles/vernye-i-neizvestnye-zdorovoe-pastyrstvo/',
      readingTime: '31 мин',
    },
    {
      id: 'zdorovaya-cerkov',
      mark: { kind: 'roman', value: 'VIII' },
      title: 'Часть VIII. Признаки здоровой церкви',
      shortTitle: 'Признаки здоровой церкви',
      href: '/articles/priznaki-zdorovoy-cerkvi/',
      readingTime: '30 мин',
    },
    {
      id: 'nesovershennyy',
      mark: { kind: 'roman', value: 'IX' },
      title: 'Часть IX. Несовершенный человек в несовершенной церкви',
      shortTitle: 'Несовершенный человек · несовершенная церковь',
      href: '/articles/nesovershennyy-chelovek-v-nesovershennoy-cerkvi/',
      readingTime: '31 мин',
    },
    {
      id: 'diotrophes',
      mark: { kind: 'label', value: 'Досье A' },
      title: 'Диотрефы нашего времени',
      shortTitle: 'Документальные кейсы · власть и верные ответы',
      href: '/articles/diotrefy-nashego-vremeni/',
      readingTime: '35 мин',
    },
  ],
  pages: {
    antisovetov: {
      id: 'antisovetov',
      label: '20 антисоветов пастору',
      title: 'Часть I. 20 антисоветов пастору',
      mobileSection: 'Двустороннее зеркало',
      partLabel: 'Часть I · Содержание',
      readingProgressDoneMin: 0,
      readingProgressPartMin: 67,
      readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: '20 антисоветов пастору',
      railCover: '../../images/pastor-series/og-20-antisovetov-pastoru.webp',
      partDialogLabel: 'Часть I · 20 антисоветов пастору',
      partToc: [
        { href: '#two-way-mirror', label: 'Двустороннее зеркало', level: 2, current: true, summary: 'Статью можно злоупотребить с обеих сторон: и пастор, и прихожанин способны манипулировать Писанием.' },
        { href: '#roots', label: 'Откуда это берётся', level: 2, summary: 'Корень всех антисоветов — идолопоклонство перед служением.' },
        { href: '#section-1', label: 'I. Сердце и авторитет', level: 2 },
        { href: '#section-2', label: 'II. Команда и ближайшее окружение', level: 2 },
        { href: '#section-3', label: 'III. Инструменты контроля', level: 2 },
        { href: '#section-iv', label: 'IV. Отношения и внутренняя культура', level: 2 },
        { href: '#section-v', label: 'V. Сокрытие, прикрытие и финал', level: 2 },
        { href: '#itog', label: 'Итог', level: 2 },
        { href: '#antidot', label: 'Как не разрушиться: антидот', level: 2 },
        { href: '#zaklyuchenie', label: 'Заключение', level: 2 },
        { href: '#hope', label: 'Надежда', level: 2 },
        { href: '#faq', label: 'FAQ: как читать трезво', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    anatomiya: {
      id: 'anatomiya', label: 'Анатомия падения', title: 'Часть II. Анатомия падения',
      mobileSection: 'Пять стадий', partLabel: 'Часть II · Содержание',
      readingProgressDoneMin: 67, readingProgressPartMin: 29, readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: 'Анатомия падения', railCover: '../../images/pastor-series/og-anatomiya-padeniya-pyat-stadiy.webp',
      partDialogLabel: 'Часть II · Анатомия падения', partToc: [
        { href: '#metod', label: 'Что эта модель утверждает — и чего не утверждает', level: 2, summary: 'Повторяемость механизмов в документированных случаях полезна, но её нельзя превращать в закон природы.' },
        { href: '#lichnoe-sistemnoe', label: 'Личный грех и системное зло — не одно', level: 2, summary: 'Система — это механизм, который защищает грех от света: подотчётность, информация, страх.' },
        { href: '#stadiya-1', label: 'Стадия 1. Служение становится платформой, которую нельзя потерять', level: 2, summary: 'Идол платформы: достижения и аудитория перестают быть для стада и становятся собственностью.' },
        { href: '#stadiya-2', label: 'Стадия 2. Подотчётность становится декоративной', level: 2, summary: 'Точка перехода: система теряет механизм, которым замечает собственные ошибки.' },
        { href: '#stadiya-3', label: 'Стадия 3. Цена вопроса становится выше самого вопроса', level: 2, summary: 'Страх управляет правдой: вопроситель рискует статусом, а вопрос остаётся без ответа.' },
        { href: '#stadiya-4', label: 'Стадия 4. Репутация начинает управлять правдой', level: 2, summary: 'Образ безупречности становится важнее, чем установление фактов.' },
        { href: '#stadiya-5', label: 'Стадия 5. Покаяние становится управлением ущербом — или начинается реформа', level: 2, summary: 'Ложное покаяние узнаётся по тому, что архитектура власти не меняется; настоящая реформа — по видимым изменениям.' },
        { href: '#tri-osi', label: 'Три оси, без которых пяти стадий недостаточно', level: 2 },
        { href: '#rannie-markery', label: 'Ранняя диагностика без охоты на ведьм', level: 2, summary: 'Маркеры наблюдаемы в устройстве, а не в настроениях: кто контролирует информацию, можно ли задать вопрос.' },
        { href: '#dvustoronnee', label: 'Двустороннее зеркало', level: 2, summary: 'Член церкви способен использовать матрицу нечестно; применение требует той же дисциплины доказательств, что и Досье A.' },
        { href: '#zaklyuchenie', label: 'Падение начинается раньше скандала — и исправление тоже', level: 2 },
        { href: '#istochniki', label: 'Исследовательская база', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    teksty: {
      id: 'teksty', label: 'Тексты Писания', title: 'Часть III. Тексты Писания, которыми манипулируют',
      mobileSection: 'Герменевтика власти', partLabel: 'Часть III · Содержание',
      readingProgressDoneMin: 96, readingProgressPartMin: 36, readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: 'Тексты Писания, которыми манипулируют', railCover: '../../images/pastor-series/og-teksty-pisaniya-kotorymi-manipuliruyut.webp',
      partDialogLabel: 'Часть III · Тексты Писания', partToc: [
        { href: '#obshchee', label: 'Пять операций над текстом', level: 2, summary: 'Изоляция от контекста, устранение подотчётности, смешение сфер власти, игнорирование жанра, асимметричное применение.' },
        { href: '#pomazanniki', label: '«Не трогай помазанника»: тексты о неприкосновенности', level: 2, summary: 'Текст ограничивает насилие, но не запрещает словесного обличения установленного греха.' },
        { href: '#ne-sudite', label: '«Не судите» и процедуры молчания', level: 2, summary: 'Запрет касается позы осуждения, а не установления фактов: в том же контексте заповедано различать по плодам.' },
        { href: '#semya-dengi', label: 'Семья, деньги, кротость и прощение', level: 2 },
        { href: '#zhanr-sokrytie', label: 'Жанр, устрашение и сокрытие', level: 2 },
        { href: '#kvalifikacii', label: 'Квалификации и духовная практика', level: 2 },
        { href: '#protivoves', label: 'Тексты, которые прямо обличают злоупотребление', level: 2, summary: 'Каждому тексту манипуляции противостоит встречный текст из того же канона: Писание судит обе стороны.' },
        { href: '#vsegda-prav', label: 'Отдельный тест: «пастор всегда прав»', level: 2, summary: 'Фраза не решается одним стихом: Евр. 13:17 требует и реального повиновения, и подотчётности наставников.' },
        { href: '#algoritm', label: 'Диагностический алгоритм', level: 2, summary: 'Восемь шагов перед «сильным стихом»: контекст, адресат, жанр, встречные обязанности, симметрия доказательств, собственное сердце.' },
        { href: '#zaklyuchenie', label: 'Один текст над обеими сторонами', level: 2, summary: 'Манипуляция заканчивается, когда обе стороны соглашаются быть исправленными тем же Словом.' },
        { href: '#istochniki', label: 'Источники и сверка', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    'sem-tipov': {
      id: 'sem-tipov', label: 'Семь типов', title: 'Часть IV. Семь типов учителей и лидеров',
      mobileSection: 'Различение лидеров', partLabel: 'Часть IV · Содержание',
      readingProgressDoneMin: 132, readingProgressPartMin: 30, readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: 'Семь типов учителей и лидеров', railCover: '../../images/pastor-series/og-sem-tipov-razlichenie-uchiteley.webp',
      partDialogLabel: 'Часть IV · Семь типов', partToc: [
        { href: '#sem-kategoriy', label: 'Семь категорий', level: 2, summary: 'Семь категорий — редакционная аналитическая модель статьи: она описывает роли и не является исчерпывающей вдохновенной классификацией.' },
        { href: '#os-kovarstva', label: 'Ось коварства внутри категории «волк»', level: 2, summary: 'Три полюса мотивов — корысть, карательная вражда и маскировка — аналитическая модель статьи, а не клиническая шкала.' },
        { href: '#eliy', label: 'Илий: попустительство вместо защиты', level: 2, summary: 'Лидер, знающий о продолжающемся вреде и обязанный действовать, отвечает и за виновное бездействие.' },
        { href: '#saul', label: 'Саул: траектория, а не готовый портрет современного лидера', level: 2, summary: 'Текст предупреждает о паттерне давления и компромиссов, но современный пастор не отождествляется с Саулом.' },
        { href: '#dve-osi', label: 'Две оси: учение и пригодность', level: 2, summary: 'Ортодоксальность сама по себе не делает человека квалифицированным пастором, а нравственный провал не следует автоматически переименовывать в доктринальную ересь.' },
        { href: '#disciplina-poiska', label: 'Дисциплина суждения', level: 2, summary: 'Четыре правила применения: только верифицированное, роли а не ярлыки, не подтягивать слабое, отделять наблюдаемое от мотива.' },
        { href: '#posleslovie', label: 'Богословское послесловие: структура важна, но не спасает', level: 2, summary: 'Категории — служебный аппарат, а не гарантия безошибочности сужающего.' },
        { href: '#istochniki', label: 'Источники и сверка', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    disciplina: {
      id: 'disciplina', label: 'Церковная дисциплина', title: 'Часть V. Церковная дисциплина: власть, границы и защита',
      mobileSection: 'Власть и защита', partLabel: 'Часть V · Содержание',
      readingProgressDoneMin: 162, readingProgressPartMin: 34, readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: 'Церковная дисциплина', railCover: '../../images/pastor-series/og-cerkovnaya-disciplina-vlast-granicy-zashchita.webp',
      partDialogLabel: 'Часть V · Церковная дисциплина', partToc: [
        { href: '#bogoslovie-vlasti', label: 'Позитивное богословие власти', level: 2, summary: 'Власть служебная и подотчётная: Церковь принадлежит Христу, а не старейшинам.' },
        { href: '#shest-sfer', label: 'Шесть уровней пастырского требования', level: 2, summary: 'От ясной заповеди до личной свободы, где «Бог один Господь совести».' },
        { href: '#mnozhestvennost', label: 'Множественность: сильный паттерн, не магический талисман', level: 2, summary: 'Численность ничего не гарантирует: критерий — реальная взаимная подотчётность.' },
        { href: '#cel', label: 'Цель дисциплины: приобрести, очистить, восстановить', level: 2, summary: 'Дисциплина служит славе Христа, святости общины, защите других, покаянию согрешившего и ясности свидетельства — а не мести церкви.' },
        { href: '#matfeya-18', label: 'Матфея 18: настоящий процесс — и его предел', level: 2, summary: 'Три шага — личное исправление, свидетели, церковь — с пределом: текст нельзя ни абсолютизировать, ни отменять.' },
        { href: '#1tim', label: '1 Тим. 5:19–20: не уничтожить пастора — и не сделать его неприкасаемым', level: 2, summary: 'Двойной предохранитель: слух не уничтожает пресвитера, но и должность не делает его неприкасаемым.' },
        { href: '#prestuplenie', label: 'Церковная дисциплина и гражданская юрисдикция', level: 2 },
        { href: '#vossem', label: 'Восемь признаков законной церковной дисциплины', level: 2 },
        { href: '#desyat', label: 'Десять признаков дисциплины, превращённой в оружие', level: 2 },
        { href: '#proshchenie', label: 'Прощение, доверие и кафедра — не одно', level: 2, summary: 'Прощение обязательно; возвращение на кафедру — вопрос публичных квалификаций и доверия.' },
        { href: '#pastor-vsegda-prav', label: 'Что делать, если пастор неправ, но решение законно', level: 2 },
        { href: '#dvustoronnee', label: 'Двустороннее зеркало', level: 2 },
        { href: '#zaklyuchenie', label: 'Власть, которая сама стоит под властью', level: 2 },
        { href: '#istochniki', label: 'Источники', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    'kogda-uhodit': {
      id: 'kogda-uhodit', label: 'Когда говорить и уходить', title: 'Часть VI. Когда говорить, молчать, уходить или оставаться',
      mobileSection: 'Решения под давлением', partLabel: 'Часть VI · Содержание',
      readingProgressDoneMin: 196, readingProgressPartMin: 33, readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: 'Когда говорить, когда уходить', railCover: '../../images/pastor-series/og-kogda-uhodit-kogda-ostavatsya.webp',
      partDialogLabel: 'Часть VI · Когда говорить и уходить', partToc: [
        { href: '#dve-kanavy', label: 'Две канавы: квиетизм и гипербдительность', level: 2, summary: 'Квиетизм называет свидетельство мятежом; гипербдительность делает различение иммунитетом. Задача — пройти между.' },
        { href: '#snachala', label: 'До решения: семь вопросов факта', level: 2, summary: 'Семь вопросов отделяют наблюдаемое от прочитанного между строк: «он сделал X» и «он сделал X, потому что боится меня» — разные уровни.' },
        { href: '#kogda-molchat', label: 'Когда молчание может быть мудростью', level: 2 },
        { href: '#kogda-govorit', label: 'Когда молчание перестаёт быть добродетелью', level: 2, summary: 'Установленный продолжающийся вред: «не выносить сор из избы» становится служением фасаду.' },
        { href: '#komu-govorit', label: 'Кому говорить: адресат имеет значение', level: 2, summary: 'Правильная информация, переданная неправильному адресату ради партии, становится сплетней и фракционностью.' },
        { href: '#ton', label: 'Тон не решает правду — но тон всё равно нравственен', level: 2 },
        { href: '#kogda-uhodit', label: 'Когда уход становится серьёзно обоснованным', level: 2 },
        { href: '#kogda-ostatsya', label: 'Когда серьёзные причины говорят в пользу того, чтобы остаться', level: 2 },
        { href: '#dvenadcat', label: 'Двенадцать вопросов перед решением', level: 2, summary: 'Двенадцать вопросов до решения: учение, факты, паттерн, власть и безопасность, совесть — и зрелые свидетели вне эмоционального пузыря.' },
        { href: '#korah-nafan', label: 'Нафан и Корей: не путать два вида сопротивления', level: 2, summary: 'Нафан — пророческое обличение установленного греха; Корей — честолюбивая фракция под благочестивой риторикой.' },
        { href: '#kak-uyti', label: 'Если уходить — как уйти без разрушения', level: 2 },
        { href: '#pastoru', label: 'Пастору: как пережить несогласие и уход человека', level: 2 },
        { href: '#esli-net-alternativy', label: 'Если рядом нет хорошей альтернативы', level: 2 },
        { href: '#zaklyuchenie', label: 'Не «оставаться любой ценой» и не «уходить при первом сигнале»', level: 2 },
        { href: '#istochniki', label: 'Источники', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    vernye: {
      id: 'vernye', label: 'Верные и неизвестные', title: 'Часть VII. Верные и неизвестные: здоровое пастырство',
      mobileSection: 'Здоровое пастырство', partLabel: 'Часть VII · Содержание',
      readingProgressDoneMin: 229, readingProgressPartMin: 31, readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: 'Верные и неизвестные', railCover: '../../images/pastor-series/og-vernye-i-neizvestnye-zdorovoe-pastyrstvo.webp',
      partDialogLabel: 'Часть VII · Верные и неизвестные', partToc: [
        { href: '#glava', label: 'Сначала Глава: пастор не владеет церковью', level: 2, summary: 'Церковь принадлежит Христу: пастор — распорядитель чужого стада, а не владелец общины.' },
        { href: '#harakter', label: 'Характер прежде платформы', level: 2, summary: 'Норма Нового Завета — не впечатляющий человек, а проверенный человек.' },
        { href: '#primer', label: 'Не господствуя, а подавая пример', level: 2 },
        { href: '#realnaya-vlast', label: 'Реальная власть — не необязательный совет', level: 2, summary: 'Опровергаются обе крайности: «только совет» слишком слабо, «пасторская абсолютность» — небиблейска.' },
        { href: '#vsegda-prav', label: '«Пастор всегда прав, даже когда неправ»', level: 2, summary: 'Уважать и законно слушаться — да; превращать пастора в последнего господина истины и совести — нет.' },
        { href: '#shest-sfer', label: 'Шесть сфер: когда повелевать, когда убеждать, когда советовать', level: 2 },
        { href: '#bog-pokazal', label: '«Мне Бог показал, что тебе нужно...»', level: 2, summary: 'Граница между сильным советом и подменой: суждение без библейской заповеди не получает иммунитет от проверки.' },
        { href: '#ispravimost', label: 'Пастор, которого можно исправить', level: 2, summary: 'Лучший тест власти — реакция на возражение: пастор, которого можно поправить без угрозы для поправляющего.' },
        { href: '#1tim5', label: 'Защищать пастора от клеветы — и церковь от неприкасаемости', level: 2 },
        { href: '#mnozhestvennost', label: 'Множественность — защита, но не талисман', level: 2 },
        { href: '#ispoved', label: '1689: Бог один Господь совести', level: 2 },
        { href: '#pokayanie', label: 'Как кается здоровый пастор', level: 2, summary: 'Покаяние конкретно и не торгуется за кафедру; прощение человека не равно возвращению на должность.' },
        { href: '#tainy', label: 'Исповедь, конфиденциальность и власть над информацией', level: 2 },
        { href: '#uhod', label: 'Когда человек уходит', level: 2 },
        { href: '#neizvestnye', label: 'Верные и неизвестные', level: 2 },
        { href: '#zerkalo', label: 'Двустороннее зеркало: что здоровый пастор вправе ожидать от церкви', level: 2 },
        { href: '#proverka', label: 'Двенадцать вопросов к здоровью пастырского служения', level: 2 },
        { href: '#zaklyuchenie', label: 'Не слабая власть, а власть под крестом', level: 2 },
        { href: '#istochniki', label: 'Источники', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    'zdorovaya-cerkov': {
      id: 'zdorovaya-cerkov', label: 'Признаки здоровой церкви', title: 'Часть VIII. Признаки здоровой церкви',
      mobileSection: 'Здоровая церковь', partLabel: 'Часть VIII · Содержание',
      readingProgressDoneMin: 260, readingProgressPartMin: 30, readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: 'Признаки здоровой церкви', railCover: '../../images/pastor-series/og-priznaki-zdorovoy-cerkvi.webp',
      partDialogLabel: 'Часть VIII · Признаки здоровой церкви', partToc: [
        { href: '#ne-ideal', label: 'Здоровая — не значит идеальная', level: 2, summary: 'Здоровье — способность обнаруживать, называть и лечить болезнь средствами, которые дал Христос.' },
        { href: '#slovo', label: '1. Слово выше личности', level: 2, summary: 'Авторитет учителя не автономный: он убедителен, пока приводит к Слову, а не заменяет его.' },
        { href: '#stareyshiny', label: '2. Старейшинство, которое действительно может остановить старейшину', level: 2, summary: 'Критерий — реальная взаимная проверка, а не численность и демонстрация единодушия.' },
        { href: '#chlenstvo', label: '3. Членство как завет ответственности, а не собственность руководства', level: 2 },
        { href: '#disciplina', label: '4. Дисциплина, в которой цель видна из процедуры', level: 2, summary: 'Цель — восстановление и святость; если результат решён заранее, процедура обслуживает его.' },
        { href: '#zhaloby', label: '5. Путь жалобы, который работает и тогда, когда жалоба на сильного', level: 2, summary: 'Настоящий тест — жалоба на того, кто контролирует большую часть системы.' },
        { href: '#1tim', label: '6. 1 Тим. 5:19–20 как двойной предохранитель', level: 2 },
        { href: '#finansy', label: '7. Деньги устроены так, чтобы доверие не заменяло контроль', level: 2, summary: 'Проверяемость не является оскорблением доверия.' },
        { href: '#informaciya', label: '8. Конфиденциальность без тайной системы', level: 2, summary: 'Конфиденциальность — «кому необходимо знать ради любви и справедливости»; секретность — «кому нельзя знать ради контроля».' },
        { href: '#voprosy', label: '9. Вопрос не считается мятежом до рассмотрения содержания', level: 2 },
        { href: '#kafedra', label: '10. Кафедра не является судом над текущими оппонентами', level: 2 },
        { href: '#pokayanie', label: '11. Покаяние меняет не только слова, но систему', level: 2 },
        { href: '#uhod', label: '12. У церкви есть достойный выход', level: 2 },
        { href: '#preemstvo', label: '13. Церковь может пережить уход сильного лидера', level: 2 },
        { href: '#zashchita', label: '14. Защита уязвимых не противопоставляется справедливости к обвиняемому', level: 2 },
        { href: '#miriane', label: '15. Здоровую церковь строят не только старейшины', level: 2 },
        { href: '#minimum', label: 'Практические контуры здорового устройства', level: 2 },
        { href: '#zaklyuchenie', label: 'Церковь, которой не страшен свет', level: 2 },
        { href: '#istochniki', label: 'Источники', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    nesovershennyy: {
      id: 'nesovershennyy', label: 'Несовершенный человек', title: 'Часть IX. Несовершенный человек в несовершенной церкви',
      mobileSection: 'Финальный предохранитель', partLabel: 'Часть IX · Содержание',
      readingProgressDoneMin: 290, readingProgressPartMin: 31, readingProgressTotalMin: CORE_TOTAL_MIN,
      railNowTitle: 'Несовершенный человек в несовершенной церкви', railCover: '../../images/pastor-series/og-nesovershennyy-chelovek-v-nesovershennoy-cerkvi.webp',
      partDialogLabel: 'Часть IX · Несовершенный человек', partToc: [
        { href: '#zachem', label: 'Почему эта часть должна быть последней', level: 2, summary: 'Диагностический язык легко превратить в линзу, через которую всё выглядит болезнью: серия заканчивается возвращением различающего под исправление собственного сердца.' },
        { href: '#ideal', label: 'Идеальная церковь не обещана', level: 2 },
        { href: '#oshibka-pattern', label: 'Ошибка и паттерн — не одно', level: 2, summary: 'Эпизод — повод для проверки, а не приговор; «все несовершенны» не оправдывает повторяющееся зло.' },
        { href: '#bol', label: 'Боль — свидетель, но не верховный судья', level: 2, summary: 'Боль открывает вопрос, а факты отвечают на него.' },
        { href: '#rezkost', label: 'Резкость не равна автоматически злоупотреблению', level: 2 },
        { href: '#net', label: '«Нет» не равно контролю', level: 2 },
        { href: '#oblichenie', label: 'Обличение не равно газлайтингу', level: 2, summary: 'Термин описывает проверяемый паттерн поведения, а не всякую жёсткость или несогласие.' },
        { href: '#sovest', label: 'Совесть не делает моё толкование непогрешимым', level: 2, summary: 'Совесть стоит под Словом и над человеком: непогрешимость и господство отвергаются обе.' },
        { href: '#avtonomiya', label: '«Я подчиняюсь только Христу» может быть благочестивой формой автономии', level: 2 },
        { href: '#ideal-pastor', label: 'Не требуйте от пастора мессианской компетентности', level: 2 },
        { href: '#spletni', label: 'Различение не даёт права на сплетню', level: 2, summary: 'Контент и канал — разные вещи: различение, переданное в мобилизующий круг, становится политикой.' },
        { href: '#koaliciya', label: 'Коалиция может быть и защитой, и мятежом', level: 2 },
        { href: '#ostatsya', label: 'Оставаться — не всегда трусость', level: 2 },
        { href: '#uyti', label: 'Уходить — не всегда верность', level: 2 },
        { href: '#proshchenie', label: 'Прощение не требует назвать зло добром', level: 2 },
        { href: '#matrica', label: 'Матрица трезвого различения', level: 2, summary: 'Матрица держит различения вместе — а финал возвращает ко Христу, Пастыреначальнику.' },
        { href: '#dvustoronnee', label: 'Последнее двустороннее зеркало', level: 2 },
        { href: '#hristos', label: 'Финал серии: Пастыреначальник', level: 2 },
        { href: '#istochniki', label: 'Источники', level: 2 },
        { href: '#sec-quiz', label: 'Проверь себя', level: 2 },
      ],
    },
    diotrophes: {
      id: 'diotrophes',
      label: 'Диотрефы нашего времени',
      title: 'Досье A. Диотрефы нашего времени',
      mobileSection: 'Документальные кейсы',
      partLabel: 'Досье A · Содержание',
      readingProgressDoneMin: 0,
      readingProgressPartMin: 35,
      readingProgressTotalMin: 35,
      railNowTitle: 'Диотрефы нашего времени',
      railCover: '../../images/pastor-series/og-20-antisovetov-pastoru.webp',
      partDialogLabel: 'Досье A · Диотрефы нашего времени',
      partToc: [
        { href: '#short-summary', label: 'Коротко', level: 2, current: true },
        { href: '#interpretive-guardrails', label: 'Границы толкования', level: 2 },
        { href: '#biblical-profile', label: 'Диотреф в 3 Ин. 9–10', level: 2 },
        { href: '#authority-capture', label: 'Захват власти', level: 2 },
        { href: '#governance-procedure', label: 'Совет и процедура', level: 2 },
        { href: '#information-reputation', label: 'Информация и репутация', level: 2 },
        { href: '#retaliation-silencing', label: 'Возмездие и молчание', level: 2 },
        { href: '#sexual-spiritual-coercion', label: 'Духовное принуждение', level: 2 },
        { href: '#financial-dependency', label: 'Финансовая зависимость', level: 2 },
        { href: '#pastoral-conclusion', label: 'Пастырский вывод', level: 2 },
        { href: '#sources', label: 'Источники Wave 10', level: 2 },
        { href: '#quiz', label: 'Проверь различения', level: 2 },
        { href: '#faithful-witness-under-pressure', label: 'Верность под давлением', level: 2 },
        { href: '#fifteen-faithful-pathways', label: '15 реальных путей', level: 2 },
        { href: '#positive-board-comparator', label: 'Совет, который действует', level: 2 },
        { href: '#twenty-faithful-responses', label: '20 верных ответов', level: 2 },
        { href: '#faithful-decision-ladder', label: 'Лестница различения', level: 2 },
      ],
    },
  },
});

SERIES_CONFIGS[PASTOR_SERIES.seriesId] = PASTOR_SERIES;
